### ISSUE TITLE
Crash while drawing target

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#114]
Crash from Google Play Console:

```
java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
    at de.dreier.mytargets.views.TargetView.onDraw(TargetView.java:180)
    at android.view.View.draw(View.java:17469)
    at android.view.View.updateDisplayListIfDirty(View.java:16464)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.View.draw(View.java:17238)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
    at android.view.View.updateDisplayListIfDirty(View.java:16459)
    at android.view.View.draw(View.java:17238)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
    at android.view.View.updateDisplayListIfDirty(View.java:16459)
    at android.view.View.draw(View.java:17238)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
    at android.view.View.updateDisplayListIfDirty(View.java:16459)
    at android.view.View.draw(View.java:17238)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
    at android.view.View.draw(View.java:17472)
    at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
    at android.view.View.updateDisplayListIfDirty(View.java:16464)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    at android.view.Choreographer.doCallbacks(Choreographer.java:695)
    at android.view.Choreographer.doFrame(Choreographer.java:631)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by DreierF** [comment]
Most probably fixed with #197
