### ISSUE TITLE
App sometimes crashes while importing a backup

### ISSUE THREAD

**Issue by DreierF** [DreierF/MyTargets#29]
The app crashes because it has problem to open the connection to the database after it has been replaced. The data is available after a app restart even if the app crashed before.

**Comment by DreierF** [comment]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:142)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/de.dreier.mytargets/databases/database
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1450)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1393)
	at de.dreier.mytargets.managers.dao.TrainingDataSource.getAll(TrainingDataSource.java:110)
	at de.dreier.mytargets.fragments.TrainingsFragment$$Lambda$1.run(TrainingsFragment.java)
	                                                             lambdaFactory$(TrainingsFragment.java)
	at de.dreier.mytargets.utils.DataLoaderBase.loadInBackground(DataLoaderBase.java:27)
	at de.dreier.mytargets.utils.DataLoaderBase.loadInBackground(DataLoaderBase.java:10)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```
